# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c8pe7p7zt-capi-aws
  namespace: c8pe7p7zt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c8pe7p7zt-capi-aws
subjects:
- kind: ServiceAccount
  name: c8pe7p7zt-capi-aws
